name: build_windows_zip_x86_64

on:
  workflow_dispatch:
    inputs:
      app-directory:
        description: "The directory where the app is located"
        required: true
        type: string
        default: ./app
      asset-path: 
        description: "Name of the generated file with its extension"
        required: false
        type: string
        default: result.zip

  workflow_call:
    inputs:
      app-directory:
        description: "The directory where the app is located"
        required: true
        type: string
      asset-path: 
        description: "Name of the generated file with its extension"
        required: false
        type: string
        default: result.zip

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get flutter dependencies
        working-directory: ${{ inputs.app-directory }}
        run: flutter pub get

      - name: Build windows app
        working-directory: ${{ inputs.app-directory }}
        run: flutter build windows

      - name: Create empty settings.json
        working-directory: ${{ inputs.app-directory }}
        run: echo {} > build/windows/x64/runner/Release/settings.json

      - name: Zip compiled files
        working-directory: ${{ inputs.app-directory }}
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath ${{ inputs.asset-path }}

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: ${{ inputs.app-directory }}/${{ inputs.asset-path }}

    outputs:
      asset_path: ${{ inputs.asset-path }}
      asset_content_type: application/zip